### ISSUE TITLE
Background location access

### ISSUE THREAD

**Issue by davidpirates** [aws-samples/amazon-location-service-mobile-tracker-react#1]
How to i get background location access which is not mentioned in this code sample.
Can you please help me to get background location access using react native ?

**Comment by sempfa** [comment]
@davidpirates This samples uses the expo framework for react native.

In order to use background location there are 2 things you need to do.

**1**: Set up task manager. 
instruction on this can be found here: [https://docs.expo.dev/versions/latest/sdk/task-manager/#configuration](https://docs.expo.dev/versions/latest/sdk/task-manager/#configuration)

**2**: make sure that permissions for location are configured. 
instruction on this can be found here: [https://docs.expo.dev/versions/latest/sdk/location/#configuration](https://docs.expo.dev/versions/latest/sdk/location/#configuration)
